# Yakov Kazinets and Tae Kim
# I pledge my honor that I have abided by the Stevens Honor System.
# used the same makefile as used in previous class assignments!
CC     = gcc
CFLAGS = -g -Wall -Werror -pedantic-errors

all:
	$(CC) $(CFLAGS) $(C_FILE) -o client client.c
	$(CC) $(CFLAGS) $(C_FILE) -o server server.c
clean:
	rm client server
