#*******************************************************************************
#* Name        : sort.c
#* Author      : Yakov Kazinets
#* Date        : 2/20/2020
#* Description : Uses quicksort to sort a file of either ints, doubles, or
#*               strings.
#* Pledge      : I pledge my honor that I have abided by the Stevens Honor System.
#******************************************************************************

gcc -Wall -Wextra main.c foo.c bar.c -O -o program -ansi -pedantic -Werror
